#!/usr/bin/env python3
"""Rebuild INDEX.md from entry frontmatter. No external dependencies.

Reads every $KB_ROOT/entries/**/*.md, parses its YAML-ish frontmatter and the first
line under '## Summary', and writes a catalog grouped by topic to $KB_ROOT/INDEX.md.
"""
import os
import re
import datetime

KB = os.environ.get("ANIMUS_HOME", os.path.expanduser("~/.claude/skills/animus"))
ENTRIES = os.path.join(KB, "entries")
INDEX = os.path.join(KB, "INDEX.md")


def parse_frontmatter(text):
    """Return (dict, body). Handles simple scalars and [a, b] lists."""
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    fm_raw, body = m.group(1), m.group(2)
    fm = {}
    for line in fm_raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            fm[key] = [v.strip().strip("'\"") for v in val[1:-1].split(",") if v.strip()]
        else:
            fm[key] = val.strip("'\"")
    return fm, body


def first_summary(body):
    """First non-empty line under a '## Summary' heading; fallback to first prose line."""
    lines = body.splitlines()
    in_summary = False
    for line in lines:
        if re.match(r"^#+\s*summary", line, re.I):
            in_summary = True
            continue
        if in_summary:
            if line.strip().startswith("#"):
                break
            if line.strip():
                return line.strip()
    for line in lines:
        if line.strip() and not line.strip().startswith("#"):
            return line.strip()
    return ""


def collect():
    out = []
    if not os.path.isdir(ENTRIES):
        return out
    for root, _, files in os.walk(ENTRIES):
        for f in sorted(files):
            if not f.endswith(".md"):
                continue
            path = os.path.join(root, f)
            with open(path, encoding="utf-8") as fh:
                fm, body = parse_frontmatter(fh.read())
            tags = fm.get("tags") or []
            if isinstance(tags, str):
                tags = [tags]
            summary = first_summary(body)
            if len(summary) > 120:
                summary = summary[:117].rstrip() + "..."
            out.append({
                "topic": fm.get("topic") or os.path.basename(os.path.dirname(path)),
                "title": fm.get("title") or f[:-3],
                "tags": tags,
                "summary": summary,
                "rel": os.path.relpath(path, KB),
            })
    return out


def main():
    entries = collect()
    by_topic = {}
    for e in entries:
        by_topic.setdefault(e["topic"], []).append(e)

    today = datetime.date.today().isoformat()
    n, t = len(entries), len(by_topic)
    lines = [
        "# Animus — Knowledge Base Index",
        "",
        f"_Auto-generated by `scripts/rebuild-index.py`. Last rebuilt: {today}. "
        f"{n} entr{'y' if n == 1 else 'ies'} across {t} topic{'' if t == 1 else 's'}._",
        "",
    ]
    if not entries:
        lines.append('_No entries yet. Ask Claude to "store" something to get started._')
    for topic in sorted(by_topic):
        lines.append(f"## {topic}")
        lines.append("")
        for e in sorted(by_topic[topic], key=lambda x: x["title"].lower()):
            tagstr = (" · tags: " + ", ".join(e["tags"])) if e["tags"] else ""
            summ = (" — " + e["summary"]) if e["summary"] else ""
            lines.append(f"- **{e['title']}** — `{e['rel']}`{summ}{tagstr}")
        lines.append("")

    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    print(f"Wrote {INDEX} ({n} entries, {t} topics).")


if __name__ == "__main__":
    main()
